version: "3.6"
services:
  pwa:
    image: repo/repository/pod-docker-hosted/pwa/pwa_v1:${PWA_TAG}
    restart: always
    hostname: pwa_v1
    ports:
      - "3000:3000"
      - "80:80"
    volumes:
      - /applog/nginx/log:/var/log/nginx
      - ./volumes/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/default.conf:/etc/nginx/conf.d/default.conf
